name: xadap
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.2
  - python=3.10.14
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - humanfriendly==10.0
      - kiwisolver==1.4.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - numpy==2.1.0
      - onnx==1.16.2
      - onnxruntime==1.19.0
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - protobuf==5.28.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scipy==1.14.1
      - six==1.16.0
      - sympy==1.13.2
      - tzdata==2024.1
